export const Navbar = () => <h2>Navbar</h2>;
export const Hero = () => <h2>Hero</h2>;
export const Objective = () => <h2>Objective</h2>;
export { default as Scale } from "./Scale";
export const Tech = () => <h2>Tech</h2>;
export const Team = () => <h2>Team</h2>;
export const Values = () => <h2>Values</h2>;
export const Testimonials = () => <h2>Testimonials</h2>;
export const Areas = () => <h2>Areas</h2>;
export const Reasons = () => <h2>Reasons</h2>;
export const Initiatives = () => <h2>Initiatives</h2>;
export const Benefits = () => <h2>Benefits</h2>;
export const Screening = () => <h2>Screening</h2>;
export const Jobs = () => <h2>Jobs</h2>;
export const Connect = () => <h2>Connect</h2>;
