name: CD (Preview)
on: pull_request
jobs:
  deploy_preview:
    name: "Deploy to Preview"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node 16 environment
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            node_modules
            .yarn
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-

      - name: Install npm dependencies
        run: yarn

      - uses: ditointernet/action-hosting-deploy@v0.1
        id: firebase_deploy
        env:
          CHANNEL_ID: ${{ github.head_ref || github.ref_name }}
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: "${{ env.CHANNEL_ID }}"
          expires: 7d
          projectId: dito-careers-page
