name: CD (Production)
on:
  push:
    branches:
      - main
jobs:
  deploy_preview:
    name: "Deploy to Production"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node 16 environment
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            node_modules
            .yarn
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-

      - name: Install npm dependencies
        run: yarn

      - name: Deploy to Production
        uses: ditointernet/action-hosting-deploy@v0.1
        id: firebase_deploy
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
          projectId: dito-careers-page
